# Lily58 Configuration
CONFIG_ZMK_KEYBOARD_NAME="Lily58"
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# RGB Underglow Settings
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y
CONFIG_ZMK_RGB_UNDERGLOW_EFFECT_BREATHING=y
CONFIG_ZMK_RGB_UNDERGLOW_EFFECT_SOLID=y
CONFIG_ZMK_RGB_UNDERGLOW_EFFECT_RAINBOW_MOOD=y
